#!/usr/bin

R1=(*_1.fastq.gz)
R2=(*_2.fastq.gz)

suffix="_1.fastq.gz"

for ((i=0;i<${#R1[@]};i++)); do
	sample=${R1[i]%$suffix}
	cutadapt --trim-n -m 35 -u 13 -U 13 -b GATCGGAAGAGCACACGTCTGAACTCCAGTCACGATCAGATCTCGTATGC -b GATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCG -b AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA -B GATCGGAAGAGCACACGTCTGAACTCCAGTCACGATCAGATCTCGTATGC -B GATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCG -B AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA -o $sample.trimmed.R1.fastq.gz -p $sample.trimmed.R2.fastq.gz ${R1[i]} ${R2[i]} > $sample.log
done
